city = [{
    "CityID": 1,
    "CityName": "北京市",
    "ProID": 1,
    "CitySort": 1
}, {
    "CityID": 2,
    "CityName": "天津市",
    "ProID": 2,
    "CitySort": 2
}, {
    "CityID": 3,
    "CityName": "上海市",
    "ProID": 9,
    "CitySort": 3
}, {
    "CityID": 4,
    "CityName": "重庆市",
    "ProID": 27,
    "CitySort": 4
}, {
    "CityID": 5,
    "CityName": "邯郸市",
    "ProID": 3,
    "CitySort": 5
}, {
    "CityID": 6,
    "CityName": "石家庄市",
    "ProID": 3,
    "CitySort": 6
}, {
    "CityID": 7,
    "CityName": "保定市",
    "ProID": 3,
    "CitySort": 7
}, {
    "CityID": 8,
    "CityName": "张家口市",
    "ProID": 3,
    "CitySort": 8
}, {
    "CityID": 9,
    "CityName": "承德市",
    "ProID": 3,
    "CitySort": 9
}, {
    "CityID": 10,
    "CityName": "唐山市",
    "ProID": 3,
    "CitySort": 10
}, {
    "CityID": 11,
    "CityName": "廊坊市",
    "ProID": 3,
    "CitySort": 11
}, {
    "CityID": 12,
    "CityName": "沧州市",
    "ProID": 3,
    "CitySort": 12
}, {
    "CityID": 13,
    "CityName": "衡水市",
    "ProID": 3,
    "CitySort": 13
}, {
    "CityID": 14,
    "CityName": "邢台市",
    "ProID": 3,
    "CitySort": 14
}, {
    "CityID": 370,
    "CityName": "澳门特别行政区",
    "ProID": 33,
    "CitySort": 370
}, {
    "CityID": 371,
    "CityName": "香港特别行政区",
    "ProID": 34,
    "CitySort": 371
}];
