District = [{
    "Id": 1,
    "DisName": "东城区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 2,
    "DisName": "西城区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 3,
    "DisName": "崇文区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 4,
    "DisName": "宣武区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 5,
    "DisName": "朝阳区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 6,
    "DisName": "丰台区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 7,
    "DisName": "石景山区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 8,
    "DisName": "海淀区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 9,
    "DisName": "门头沟区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 10,
    "DisName": "房山区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 11,
    "DisName": "通州区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 12,
    "DisName": "顺义区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 13,
    "DisName": "昌平区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 14,
    "DisName": "大兴区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 15,
    "DisName": "怀柔区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 16,
    "DisName": "平谷区",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 17,
    "DisName": "密云县",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 18,
    "DisName": "延庆县",
    "CityID": 1,
    "DisSort": null
}, {
    "Id": 19,
    "DisName": "和平区",
    "CityID": 2,
    "DisSort": null
}, {
    "Id": 20,
    "DisName": "河东区",
    "CityID": 2,
    "DisSort": null
}, {
    "Id": 21,
    "DisName": "河西区",
    "CityID": 2,
    "DisSort": null
}, {
    "Id": 22,
    "DisName": "南开区",
    "CityID": 2,
    "DisSort": null
}, {
    "Id": 23,
    "DisName": "河北区",
    "CityID": 2,
    "DisSort": null
}, {
    "Id": 2821,
    "DisName": "突泉县",
    "CityID": 361,
    "DisSort": null
}, {
    "Id": 2822,
    "DisName": "阿拉善左旗",
    "CityID": 362,
    "DisSort": null
}, {
    "Id": 2823,
    "DisName": "阿拉善右旗",
    "CityID": 362,
    "DisSort": null
}, {
    "Id": 2824,
    "DisName": "额济纳旗",
    "CityID": 362,
    "DisSort": null
}];
